CC = g++

CFLAGS = -w
LFLAGS = -lopencv_core -lopencv_imgproc -lopencv_highgui

INC = /usr/local/include
LIB = /usr/local/lib

all:
	$(CC) simple_viewer.cpp -o simple_viewer $(CFLAGS) -I$(INC) -L$(LIB) $(LFLAGS)